# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Write Configuration Data to an INI File
#'
#' This function converts an R list structure into an INI file format and writes it to a specified file.
#'
#' @param config_list A named list where each element is itself a named list representing sections and key-value pairs of the configuration data.
#' @param filename A string specifying the path to the output INI file.
#'
#' @details
#' The `config_list` parameter should be a named list where each top-level name represents a section in the INI file.
#' Each section should be a named list where the names are the keys and the values are the corresponding values in the INI file.
#' Numeric values are converted to strings before being written to the file.
#'
#' If the `config_list` is empty, an empty INI file will be created.
#'
#' @return
#' This function does not return a value. It writes the INI file to the specified path.
#'
#' @examples
#' config <- list(
#'   section1 = list(
#'     key1 = "value1",
#'     key2 = 123
#'   ),
#'   section2 = list(
#'     keyA = "valueA",
#'     keyB = "valueB"
#'   )
#' )
#' ini_file <- tempfile()
#' write_ini(config, ini_file)
#' unlink(ini_file)
#'
#' @useDynLib inih _inih_write_ini
#' @importFrom Rcpp evalCpp
#' @export
write_ini <- function(config_list, filename) {
    invisible(.Call('_inih_write_ini', PACKAGE = 'inih', config_list, filename))
}

#' Read Configuration Data from an INI File
#'
#' This function reads an INI file and converts its contents into an R list structure.
#'
#' @param filename A string specifying the path to the input INI file.
#'
#' @details
#' The `read_ini` function parses the specified INI file and converts its sections
#' and key-value pairs into a nested R list. Each section in the INI file becomes
#' a named list within the result, and each key-value pair within a section becomes
#' an element of that list.
#'
#' If the INI file cannot be loaded, the function will raise an error.
#'
#' @return
#' A named list where each element is itself a named list representing sections
#' and key-value pairs of the configuration data.
#'
#' @examples
#' config <- list(
#'     section1 = list(
#'       key1 = "value1"
#'     ),
#'     section2 = list(
#'       keyA = "valueA",
#'       keyB = "valueB"
#'     )
#' )
#'  ini_file <- tempfile()
#'  write_ini(config, ini_file)
#'  read_ini(ini_file)
#'
#'  unlink(ini_file)
#'
#' @useDynLib inih _inih_read_ini
#' @importFrom Rcpp evalCpp
#' @export
read_ini <- function(filename) {
    .Call('_inih_read_ini', PACKAGE = 'inih', filename)
}

